# Generated by Django 2.1.5 on 2019-07-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo_main',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
