# Generated by Django 2.1.5 on 2019-07-21 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_product_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time_stamp', models.DateField(default=datetime.datetime.now)),
                ('active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(to='Products.Product')),
            ],
        ),
    ]
