# Generated by Django 2.1.5 on 2019-07-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='products',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
